# Generated by Django 4.0.4 on 2022-05-30 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='MeasurementTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(verbose_name='Температура')),
                ('date_measure', models.DateField(auto_now=True, verbose_name='Дата измерения')),
                ('name_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MT', to='measurement.sensor')),
            ],
        ),
    ]
